### ISSUE TITLE
when deploying to koyeb it shows import dotenv  ModuleNotFoundError: No module named 'dotenv'l

### ISSUE THREAD

**Issue by modapksfree** [Sachinanand99/File-Sharing-Telegram-bot#16]
logs here :- 
Instance created. Preparing to start...
Instance is starting. Propagating network configuration...
Application exited with code 1. This usually indicates an application failure. Check that the command used to launch your application is correct.
Instance stopped
Instance created. Preparing to start...
Traceback (most recent call last):
  File "/workspace/main.py", line 1, in <module>
    from bot import Bot
  File "/workspace/bot.py", line 2, in <module>
    from database.database import full_adminbase
  File "/workspace/database/database.py", line 3, in <module>
    from config import ADMINS, DB_URL, DB_NAME
  File "/workspace/config.py", line 4, in <module>
    import dotenv
ModuleNotFoundError: No module named 'dotenv'
Instance is starting. Propagating network configuration...
Traceback (most recent call last):
  File "/workspace/main.py", line 1, in <module>
    from bot import Bot
  File "/workspace/bot.py", line 2, in <module>
    from database.database import full_adminbase
  File "/workspace/database/database.py", line 3, in <module>
    from config import ADMINS, DB_URL, DB_NAME
  File "/workspace/config.py", line 4, in <module>
    import dotenv
ModuleNotFoundError: No module named 'dotenv'
Application exited with code 1. This usually indicates an application failure. Check that the command used to launch your application is correct.
Instance stopped

**Comment by Sachinanand99** [comment]
fixed
